name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set Git committer identity
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"  # Use your GitHub email here

      - name: Pull latest changes for submodules (auto resolve conflicts)
        run: |
          git submodule foreach 'git fetch && git merge -X theirs || true'
        
      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.wk_token }}  
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Beep-Boop: Update submodules with merged changes"
            
            # Set up authentication using your Personal Access Token (PAT)
            git remote set-url origin https://$TOKEN@github.com/WatermelonKatanaDevs/WatermelonKatana.git

            # Push changes as your account (using your PAT for authentication)
            git push origin HEAD
          else
            echo "No changes in submodules to commit."
          fi
